/*
 * BrAPI implementation for PIPPA
 * A first draft implementation of the breeding API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.brapi.client.api;

import org.brapi.client.ApiException;
import org.brapi.client.model.PhenotypeSearchResult;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PhenotypeApi
 */
@Ignore
public class PhenotypeApiTest {

    private final PhenotypeApi api = new PhenotypeApi();

    
    /**
     * Returns a list of phenotypes
     *
     * Note: the API definition here is subject to change...
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void phenotypeSearchTest() throws ApiException {
        String germplasmDbIds = null;
        String studyDbIds = null;
        String programDbIds = null;
        String observationVariableDbIds = null;
        Integer pageSize = null;
        Integer page = null;
        PhenotypeSearchResult response = api.phenotypeSearch(germplasmDbIds, studyDbIds, programDbIds, observationVariableDbIds, pageSize, page);

        // TODO: test validations
    }
    
}
