/*
 * BrAPI implementation for PIPPA
 * A first draft implementation of the breeding API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.brapi.client.api;

import org.brapi.client.ApiCallback;
import org.brapi.client.ApiClient;
import org.brapi.client.ApiException;
import org.brapi.client.ApiResponse;
import org.brapi.client.Configuration;
import org.brapi.client.Pair;
import org.brapi.client.ProgressRequestBody;
import org.brapi.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.brapi.client.model.StudyResult;
import org.brapi.client.model.StudySearchResult;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class StudyApi {
    private ApiClient apiClient;

    public StudyApi() {
        this(Configuration.getDefaultApiClient());
    }

    public StudyApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /* Build call for studyDetails */
    private com.squareup.okhttp.Call studyDetailsCall(String studyDbId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/brapi/v1/studies/{studyDbId}".replaceAll("\\{format\\}","json")
        .replaceAll("\\{" + "studyDbId" + "\\}", apiClient.escapeString(studyDbId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call studyDetailsValidateBeforeCall(String studyDbId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'studyDbId' is set
        if (studyDbId == null) {
            throw new ApiException("Missing the required parameter 'studyDbId' when calling studyDetails(Async)");
        }
        
        
        com.squareup.okhttp.Call call = studyDetailsCall(studyDbId, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Returns a list of studies
     * 
     * @param studyDbId Get study by studyDbId (required)
     * @return StudyResult
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public StudyResult studyDetails(String studyDbId) throws ApiException {
        ApiResponse<StudyResult> resp = studyDetailsWithHttpInfo(studyDbId);
        return resp.getData();
    }

    /**
     * Returns a list of studies
     * 
     * @param studyDbId Get study by studyDbId (required)
     * @return ApiResponse&lt;StudyResult&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<StudyResult> studyDetailsWithHttpInfo(String studyDbId) throws ApiException {
        com.squareup.okhttp.Call call = studyDetailsValidateBeforeCall(studyDbId, null, null);
        Type localVarReturnType = new TypeToken<StudyResult>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Returns a list of studies (asynchronously)
     * 
     * @param studyDbId Get study by studyDbId (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call studyDetailsAsync(String studyDbId, final ApiCallback<StudyResult> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = studyDetailsValidateBeforeCall(studyDbId, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<StudyResult>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /* Build call for studySearch */
    private com.squareup.okhttp.Call studySearchCall(List<String> germplasmDbIds, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/brapi/v1/studies-search".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        if (germplasmDbIds != null)
        localVarFormParams.put("germplasmDbIds", germplasmDbIds);

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call studySearchValidateBeforeCall(List<String> germplasmDbIds, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        
        com.squareup.okhttp.Call call = studySearchCall(germplasmDbIds, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Returns a list of studies
     * 
     * @param germplasmDbIds Filter studies by germplasms used in it (optional)
     * @return StudySearchResult
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public StudySearchResult studySearch(List<String> germplasmDbIds) throws ApiException {
        ApiResponse<StudySearchResult> resp = studySearchWithHttpInfo(germplasmDbIds);
        return resp.getData();
    }

    /**
     * Returns a list of studies
     * 
     * @param germplasmDbIds Filter studies by germplasms used in it (optional)
     * @return ApiResponse&lt;StudySearchResult&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<StudySearchResult> studySearchWithHttpInfo(List<String> germplasmDbIds) throws ApiException {
        com.squareup.okhttp.Call call = studySearchValidateBeforeCall(germplasmDbIds, null, null);
        Type localVarReturnType = new TypeToken<StudySearchResult>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Returns a list of studies (asynchronously)
     * 
     * @param germplasmDbIds Filter studies by germplasms used in it (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call studySearchAsync(List<String> germplasmDbIds, final ApiCallback<StudySearchResult> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = studySearchValidateBeforeCall(germplasmDbIds, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<StudySearchResult>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
