/*
 * BrAPI implementation for PIPPA
 * A first draft implementation of the breeding API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.brapi.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.brapi.client.model.GermplasmDonor;

/**
 * Germplasm
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-31T12:16:05.949+02:00")
public class Germplasm {
  @SerializedName("germplasmDbId")
  private Integer germplasmDbId = null;

  @SerializedName("defaultDisplayName")
  private String defaultDisplayName = null;

  @SerializedName("accessionNumber")
  private String accessionNumber = null;

  @SerializedName("germplasmName")
  private String germplasmName = null;

  @SerializedName("germplasmPUI")
  private String germplasmPUI = null;

  @SerializedName("pedigree")
  private String pedigree = null;

  @SerializedName("germplasmSeedSource")
  private String germplasmSeedSource = null;

  @SerializedName("synonyms")
  private String synonyms = null;

  @SerializedName("commonCropName")
  private String commonCropName = null;

  @SerializedName("instituteCode")
  private String instituteCode = null;

  @SerializedName("instituteName")
  private String instituteName = null;

  @SerializedName("biologicalStatusOfAccessionCode")
  private String biologicalStatusOfAccessionCode = null;

  @SerializedName("countryOfOriginCode")
  private String countryOfOriginCode = null;

  @SerializedName("typeOfGermplasmStorageCode")
  private String typeOfGermplasmStorageCode = null;

  @SerializedName("genus")
  private String genus = null;

  @SerializedName("species")
  private String species = null;

  @SerializedName("speciesAuthority")
  private String speciesAuthority = null;

  @SerializedName("subtaxa")
  private String subtaxa = null;

  @SerializedName("subtaxaAuthority")
  private String subtaxaAuthority = null;

  @SerializedName("donors")
  private List<GermplasmDonor> donors = new ArrayList<GermplasmDonor>();

  @SerializedName("acquisitionDate")
  private String acquisitionDate = null;

  public Germplasm germplasmDbId(Integer germplasmDbId) {
    this.germplasmDbId = germplasmDbId;
    return this;
  }

   /**
   * Get germplasmDbId
   * @return germplasmDbId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getGermplasmDbId() {
    return germplasmDbId;
  }

  public void setGermplasmDbId(Integer germplasmDbId) {
    this.germplasmDbId = germplasmDbId;
  }

  public Germplasm defaultDisplayName(String defaultDisplayName) {
    this.defaultDisplayName = defaultDisplayName;
    return this;
  }

   /**
   * Get defaultDisplayName
   * @return defaultDisplayName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDefaultDisplayName() {
    return defaultDisplayName;
  }

  public void setDefaultDisplayName(String defaultDisplayName) {
    this.defaultDisplayName = defaultDisplayName;
  }

  public Germplasm accessionNumber(String accessionNumber) {
    this.accessionNumber = accessionNumber;
    return this;
  }

   /**
   * Get accessionNumber
   * @return accessionNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAccessionNumber() {
    return accessionNumber;
  }

  public void setAccessionNumber(String accessionNumber) {
    this.accessionNumber = accessionNumber;
  }

  public Germplasm germplasmName(String germplasmName) {
    this.germplasmName = germplasmName;
    return this;
  }

   /**
   * Get germplasmName
   * @return germplasmName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGermplasmName() {
    return germplasmName;
  }

  public void setGermplasmName(String germplasmName) {
    this.germplasmName = germplasmName;
  }

  public Germplasm germplasmPUI(String germplasmPUI) {
    this.germplasmPUI = germplasmPUI;
    return this;
  }

   /**
   * Get germplasmPUI
   * @return germplasmPUI
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGermplasmPUI() {
    return germplasmPUI;
  }

  public void setGermplasmPUI(String germplasmPUI) {
    this.germplasmPUI = germplasmPUI;
  }

  public Germplasm pedigree(String pedigree) {
    this.pedigree = pedigree;
    return this;
  }

   /**
   * Get pedigree
   * @return pedigree
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPedigree() {
    return pedigree;
  }

  public void setPedigree(String pedigree) {
    this.pedigree = pedigree;
  }

  public Germplasm germplasmSeedSource(String germplasmSeedSource) {
    this.germplasmSeedSource = germplasmSeedSource;
    return this;
  }

   /**
   * Get germplasmSeedSource
   * @return germplasmSeedSource
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGermplasmSeedSource() {
    return germplasmSeedSource;
  }

  public void setGermplasmSeedSource(String germplasmSeedSource) {
    this.germplasmSeedSource = germplasmSeedSource;
  }

  public Germplasm synonyms(String synonyms) {
    this.synonyms = synonyms;
    return this;
  }

   /**
   * Get synonyms
   * @return synonyms
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSynonyms() {
    return synonyms;
  }

  public void setSynonyms(String synonyms) {
    this.synonyms = synonyms;
  }

  public Germplasm commonCropName(String commonCropName) {
    this.commonCropName = commonCropName;
    return this;
  }

   /**
   * Get commonCropName
   * @return commonCropName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCommonCropName() {
    return commonCropName;
  }

  public void setCommonCropName(String commonCropName) {
    this.commonCropName = commonCropName;
  }

  public Germplasm instituteCode(String instituteCode) {
    this.instituteCode = instituteCode;
    return this;
  }

   /**
   * Get instituteCode
   * @return instituteCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getInstituteCode() {
    return instituteCode;
  }

  public void setInstituteCode(String instituteCode) {
    this.instituteCode = instituteCode;
  }

  public Germplasm instituteName(String instituteName) {
    this.instituteName = instituteName;
    return this;
  }

   /**
   * Get instituteName
   * @return instituteName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getInstituteName() {
    return instituteName;
  }

  public void setInstituteName(String instituteName) {
    this.instituteName = instituteName;
  }

  public Germplasm biologicalStatusOfAccessionCode(String biologicalStatusOfAccessionCode) {
    this.biologicalStatusOfAccessionCode = biologicalStatusOfAccessionCode;
    return this;
  }

   /**
   * Get biologicalStatusOfAccessionCode
   * @return biologicalStatusOfAccessionCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBiologicalStatusOfAccessionCode() {
    return biologicalStatusOfAccessionCode;
  }

  public void setBiologicalStatusOfAccessionCode(String biologicalStatusOfAccessionCode) {
    this.biologicalStatusOfAccessionCode = biologicalStatusOfAccessionCode;
  }

  public Germplasm countryOfOriginCode(String countryOfOriginCode) {
    this.countryOfOriginCode = countryOfOriginCode;
    return this;
  }

   /**
   * Get countryOfOriginCode
   * @return countryOfOriginCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCountryOfOriginCode() {
    return countryOfOriginCode;
  }

  public void setCountryOfOriginCode(String countryOfOriginCode) {
    this.countryOfOriginCode = countryOfOriginCode;
  }

  public Germplasm typeOfGermplasmStorageCode(String typeOfGermplasmStorageCode) {
    this.typeOfGermplasmStorageCode = typeOfGermplasmStorageCode;
    return this;
  }

   /**
   * Get typeOfGermplasmStorageCode
   * @return typeOfGermplasmStorageCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTypeOfGermplasmStorageCode() {
    return typeOfGermplasmStorageCode;
  }

  public void setTypeOfGermplasmStorageCode(String typeOfGermplasmStorageCode) {
    this.typeOfGermplasmStorageCode = typeOfGermplasmStorageCode;
  }

  public Germplasm genus(String genus) {
    this.genus = genus;
    return this;
  }

   /**
   * Get genus
   * @return genus
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGenus() {
    return genus;
  }

  public void setGenus(String genus) {
    this.genus = genus;
  }

  public Germplasm species(String species) {
    this.species = species;
    return this;
  }

   /**
   * Get species
   * @return species
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSpecies() {
    return species;
  }

  public void setSpecies(String species) {
    this.species = species;
  }

  public Germplasm speciesAuthority(String speciesAuthority) {
    this.speciesAuthority = speciesAuthority;
    return this;
  }

   /**
   * Get speciesAuthority
   * @return speciesAuthority
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSpeciesAuthority() {
    return speciesAuthority;
  }

  public void setSpeciesAuthority(String speciesAuthority) {
    this.speciesAuthority = speciesAuthority;
  }

  public Germplasm subtaxa(String subtaxa) {
    this.subtaxa = subtaxa;
    return this;
  }

   /**
   * Get subtaxa
   * @return subtaxa
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSubtaxa() {
    return subtaxa;
  }

  public void setSubtaxa(String subtaxa) {
    this.subtaxa = subtaxa;
  }

  public Germplasm subtaxaAuthority(String subtaxaAuthority) {
    this.subtaxaAuthority = subtaxaAuthority;
    return this;
  }

   /**
   * Get subtaxaAuthority
   * @return subtaxaAuthority
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSubtaxaAuthority() {
    return subtaxaAuthority;
  }

  public void setSubtaxaAuthority(String subtaxaAuthority) {
    this.subtaxaAuthority = subtaxaAuthority;
  }

  public Germplasm donors(List<GermplasmDonor> donors) {
    this.donors = donors;
    return this;
  }

  public Germplasm addDonorsItem(GermplasmDonor donorsItem) {
    this.donors.add(donorsItem);
    return this;
  }

   /**
   * Get donors
   * @return donors
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<GermplasmDonor> getDonors() {
    return donors;
  }

  public void setDonors(List<GermplasmDonor> donors) {
    this.donors = donors;
  }

  public Germplasm acquisitionDate(String acquisitionDate) {
    this.acquisitionDate = acquisitionDate;
    return this;
  }

   /**
   * Get acquisitionDate
   * @return acquisitionDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAcquisitionDate() {
    return acquisitionDate;
  }

  public void setAcquisitionDate(String acquisitionDate) {
    this.acquisitionDate = acquisitionDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Germplasm germplasm = (Germplasm) o;
    return Objects.equals(this.germplasmDbId, germplasm.germplasmDbId) &&
        Objects.equals(this.defaultDisplayName, germplasm.defaultDisplayName) &&
        Objects.equals(this.accessionNumber, germplasm.accessionNumber) &&
        Objects.equals(this.germplasmName, germplasm.germplasmName) &&
        Objects.equals(this.germplasmPUI, germplasm.germplasmPUI) &&
        Objects.equals(this.pedigree, germplasm.pedigree) &&
        Objects.equals(this.germplasmSeedSource, germplasm.germplasmSeedSource) &&
        Objects.equals(this.synonyms, germplasm.synonyms) &&
        Objects.equals(this.commonCropName, germplasm.commonCropName) &&
        Objects.equals(this.instituteCode, germplasm.instituteCode) &&
        Objects.equals(this.instituteName, germplasm.instituteName) &&
        Objects.equals(this.biologicalStatusOfAccessionCode, germplasm.biologicalStatusOfAccessionCode) &&
        Objects.equals(this.countryOfOriginCode, germplasm.countryOfOriginCode) &&
        Objects.equals(this.typeOfGermplasmStorageCode, germplasm.typeOfGermplasmStorageCode) &&
        Objects.equals(this.genus, germplasm.genus) &&
        Objects.equals(this.species, germplasm.species) &&
        Objects.equals(this.speciesAuthority, germplasm.speciesAuthority) &&
        Objects.equals(this.subtaxa, germplasm.subtaxa) &&
        Objects.equals(this.subtaxaAuthority, germplasm.subtaxaAuthority) &&
        Objects.equals(this.donors, germplasm.donors) &&
        Objects.equals(this.acquisitionDate, germplasm.acquisitionDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(germplasmDbId, defaultDisplayName, accessionNumber, germplasmName, germplasmPUI, pedigree, germplasmSeedSource, synonyms, commonCropName, instituteCode, instituteName, biologicalStatusOfAccessionCode, countryOfOriginCode, typeOfGermplasmStorageCode, genus, species, speciesAuthority, subtaxa, subtaxaAuthority, donors, acquisitionDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Germplasm {\n");
    
    sb.append("    germplasmDbId: ").append(toIndentedString(germplasmDbId)).append("\n");
    sb.append("    defaultDisplayName: ").append(toIndentedString(defaultDisplayName)).append("\n");
    sb.append("    accessionNumber: ").append(toIndentedString(accessionNumber)).append("\n");
    sb.append("    germplasmName: ").append(toIndentedString(germplasmName)).append("\n");
    sb.append("    germplasmPUI: ").append(toIndentedString(germplasmPUI)).append("\n");
    sb.append("    pedigree: ").append(toIndentedString(pedigree)).append("\n");
    sb.append("    germplasmSeedSource: ").append(toIndentedString(germplasmSeedSource)).append("\n");
    sb.append("    synonyms: ").append(toIndentedString(synonyms)).append("\n");
    sb.append("    commonCropName: ").append(toIndentedString(commonCropName)).append("\n");
    sb.append("    instituteCode: ").append(toIndentedString(instituteCode)).append("\n");
    sb.append("    instituteName: ").append(toIndentedString(instituteName)).append("\n");
    sb.append("    biologicalStatusOfAccessionCode: ").append(toIndentedString(biologicalStatusOfAccessionCode)).append("\n");
    sb.append("    countryOfOriginCode: ").append(toIndentedString(countryOfOriginCode)).append("\n");
    sb.append("    typeOfGermplasmStorageCode: ").append(toIndentedString(typeOfGermplasmStorageCode)).append("\n");
    sb.append("    genus: ").append(toIndentedString(genus)).append("\n");
    sb.append("    species: ").append(toIndentedString(species)).append("\n");
    sb.append("    speciesAuthority: ").append(toIndentedString(speciesAuthority)).append("\n");
    sb.append("    subtaxa: ").append(toIndentedString(subtaxa)).append("\n");
    sb.append("    subtaxaAuthority: ").append(toIndentedString(subtaxaAuthority)).append("\n");
    sb.append("    donors: ").append(toIndentedString(donors)).append("\n");
    sb.append("    acquisitionDate: ").append(toIndentedString(acquisitionDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

