/*
 * BrAPI implementation for PIPPA
 * A first draft implementation of the breeding API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.brapi.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * GermplasmDonor
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-31T12:16:05.949+02:00")
public class GermplasmDonor {
  @SerializedName("donorAccessionNumber")
  private String donorAccessionNumber = null;

  @SerializedName("donorInstituteCode")
  private String donorInstituteCode = null;

  @SerializedName("germplasmPUI")
  private String germplasmPUI = null;

  public GermplasmDonor donorAccessionNumber(String donorAccessionNumber) {
    this.donorAccessionNumber = donorAccessionNumber;
    return this;
  }

   /**
   * Get donorAccessionNumber
   * @return donorAccessionNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDonorAccessionNumber() {
    return donorAccessionNumber;
  }

  public void setDonorAccessionNumber(String donorAccessionNumber) {
    this.donorAccessionNumber = donorAccessionNumber;
  }

  public GermplasmDonor donorInstituteCode(String donorInstituteCode) {
    this.donorInstituteCode = donorInstituteCode;
    return this;
  }

   /**
   * Get donorInstituteCode
   * @return donorInstituteCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDonorInstituteCode() {
    return donorInstituteCode;
  }

  public void setDonorInstituteCode(String donorInstituteCode) {
    this.donorInstituteCode = donorInstituteCode;
  }

  public GermplasmDonor germplasmPUI(String germplasmPUI) {
    this.germplasmPUI = germplasmPUI;
    return this;
  }

   /**
   * Get germplasmPUI
   * @return germplasmPUI
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGermplasmPUI() {
    return germplasmPUI;
  }

  public void setGermplasmPUI(String germplasmPUI) {
    this.germplasmPUI = germplasmPUI;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GermplasmDonor germplasmDonor = (GermplasmDonor) o;
    return Objects.equals(this.donorAccessionNumber, germplasmDonor.donorAccessionNumber) &&
        Objects.equals(this.donorInstituteCode, germplasmDonor.donorInstituteCode) &&
        Objects.equals(this.germplasmPUI, germplasmDonor.germplasmPUI);
  }

  @Override
  public int hashCode() {
    return Objects.hash(donorAccessionNumber, donorInstituteCode, germplasmPUI);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GermplasmDonor {\n");
    
    sb.append("    donorAccessionNumber: ").append(toIndentedString(donorAccessionNumber)).append("\n");
    sb.append("    donorInstituteCode: ").append(toIndentedString(donorInstituteCode)).append("\n");
    sb.append("    germplasmPUI: ").append(toIndentedString(germplasmPUI)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

