/*
 * BrAPI implementation for PIPPA
 * A first draft implementation of the breeding API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.brapi.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.brapi.client.model.Pagination;

/**
 * Metadata
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-31T12:16:05.949+02:00")
public class Metadata {
  @SerializedName("status")
  private String status = null;

  @SerializedName("datafiles")
  private List<String> datafiles = new ArrayList<String>();

  @SerializedName("pagination")
  private Pagination pagination = null;

  public Metadata status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Metadata datafiles(List<String> datafiles) {
    this.datafiles = datafiles;
    return this;
  }

  public Metadata addDatafilesItem(String datafilesItem) {
    this.datafiles.add(datafilesItem);
    return this;
  }

   /**
   * Get datafiles
   * @return datafiles
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getDatafiles() {
    return datafiles;
  }

  public void setDatafiles(List<String> datafiles) {
    this.datafiles = datafiles;
  }

  public Metadata pagination(Pagination pagination) {
    this.pagination = pagination;
    return this;
  }

   /**
   * Get pagination
   * @return pagination
  **/
  @ApiModelProperty(example = "null", value = "")
  public Pagination getPagination() {
    return pagination;
  }

  public void setPagination(Pagination pagination) {
    this.pagination = pagination;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Metadata metadata = (Metadata) o;
    return Objects.equals(this.status, metadata.status) &&
        Objects.equals(this.datafiles, metadata.datafiles) &&
        Objects.equals(this.pagination, metadata.pagination);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, datafiles, pagination);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Metadata {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    datafiles: ").append(toIndentedString(datafiles)).append("\n");
    sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

