/*
 * BrAPI implementation for PIPPA
 * A first draft implementation of the breeding API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.brapi.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Phenotype
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-31T12:16:05.949+02:00")
public class Phenotype {
  @SerializedName("observationDbId")
  private String observationDbId = null;

  @SerializedName("observationUnitDbId")
  private String observationUnitDbId = null;

  @SerializedName("observationUnitName")
  private String observationUnitName = null;

  @SerializedName("studyDbId")
  private String studyDbId = null;

  @SerializedName("studyName")
  private String studyName = null;

  @SerializedName("studyLocationDbId")
  private String studyLocationDbId = null;

  @SerializedName("studyLocation")
  private String studyLocation = null;

  @SerializedName("programName")
  private String programName = null;

  @SerializedName("observationLevel")
  private String observationLevel = null;

  @SerializedName("germplasmDbId")
  private String germplasmDbId = null;

  @SerializedName("germplasmName")
  private String germplasmName = null;

  @SerializedName("observationVariableId")
  private String observationVariableId = null;

  @SerializedName("observationVariableDbId")
  private String observationVariableDbId = null;

  @SerializedName("season")
  private String season = null;

  @SerializedName("value")
  private String value = null;

  @SerializedName("observationTimeStamp")
  private String observationTimeStamp = null;

  @SerializedName("collector")
  private String collector = null;

  @SerializedName("uploadedBy")
  private String uploadedBy = null;

  @SerializedName("additionalInfo")
  private Object additionalInfo = null;

  public Phenotype observationDbId(String observationDbId) {
    this.observationDbId = observationDbId;
    return this;
  }

   /**
   * Get observationDbId
   * @return observationDbId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getObservationDbId() {
    return observationDbId;
  }

  public void setObservationDbId(String observationDbId) {
    this.observationDbId = observationDbId;
  }

  public Phenotype observationUnitDbId(String observationUnitDbId) {
    this.observationUnitDbId = observationUnitDbId;
    return this;
  }

   /**
   * Get observationUnitDbId
   * @return observationUnitDbId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getObservationUnitDbId() {
    return observationUnitDbId;
  }

  public void setObservationUnitDbId(String observationUnitDbId) {
    this.observationUnitDbId = observationUnitDbId;
  }

  public Phenotype observationUnitName(String observationUnitName) {
    this.observationUnitName = observationUnitName;
    return this;
  }

   /**
   * Get observationUnitName
   * @return observationUnitName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getObservationUnitName() {
    return observationUnitName;
  }

  public void setObservationUnitName(String observationUnitName) {
    this.observationUnitName = observationUnitName;
  }

  public Phenotype studyDbId(String studyDbId) {
    this.studyDbId = studyDbId;
    return this;
  }

   /**
   * Get studyDbId
   * @return studyDbId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStudyDbId() {
    return studyDbId;
  }

  public void setStudyDbId(String studyDbId) {
    this.studyDbId = studyDbId;
  }

  public Phenotype studyName(String studyName) {
    this.studyName = studyName;
    return this;
  }

   /**
   * Get studyName
   * @return studyName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStudyName() {
    return studyName;
  }

  public void setStudyName(String studyName) {
    this.studyName = studyName;
  }

  public Phenotype studyLocationDbId(String studyLocationDbId) {
    this.studyLocationDbId = studyLocationDbId;
    return this;
  }

   /**
   * Get studyLocationDbId
   * @return studyLocationDbId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStudyLocationDbId() {
    return studyLocationDbId;
  }

  public void setStudyLocationDbId(String studyLocationDbId) {
    this.studyLocationDbId = studyLocationDbId;
  }

  public Phenotype studyLocation(String studyLocation) {
    this.studyLocation = studyLocation;
    return this;
  }

   /**
   * Get studyLocation
   * @return studyLocation
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStudyLocation() {
    return studyLocation;
  }

  public void setStudyLocation(String studyLocation) {
    this.studyLocation = studyLocation;
  }

  public Phenotype programName(String programName) {
    this.programName = programName;
    return this;
  }

   /**
   * Get programName
   * @return programName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getProgramName() {
    return programName;
  }

  public void setProgramName(String programName) {
    this.programName = programName;
  }

  public Phenotype observationLevel(String observationLevel) {
    this.observationLevel = observationLevel;
    return this;
  }

   /**
   * Get observationLevel
   * @return observationLevel
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getObservationLevel() {
    return observationLevel;
  }

  public void setObservationLevel(String observationLevel) {
    this.observationLevel = observationLevel;
  }

  public Phenotype germplasmDbId(String germplasmDbId) {
    this.germplasmDbId = germplasmDbId;
    return this;
  }

   /**
   * Get germplasmDbId
   * @return germplasmDbId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGermplasmDbId() {
    return germplasmDbId;
  }

  public void setGermplasmDbId(String germplasmDbId) {
    this.germplasmDbId = germplasmDbId;
  }

  public Phenotype germplasmName(String germplasmName) {
    this.germplasmName = germplasmName;
    return this;
  }

   /**
   * Get germplasmName
   * @return germplasmName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGermplasmName() {
    return germplasmName;
  }

  public void setGermplasmName(String germplasmName) {
    this.germplasmName = germplasmName;
  }

  public Phenotype observationVariableId(String observationVariableId) {
    this.observationVariableId = observationVariableId;
    return this;
  }

   /**
   * Get observationVariableId
   * @return observationVariableId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getObservationVariableId() {
    return observationVariableId;
  }

  public void setObservationVariableId(String observationVariableId) {
    this.observationVariableId = observationVariableId;
  }

  public Phenotype observationVariableDbId(String observationVariableDbId) {
    this.observationVariableDbId = observationVariableDbId;
    return this;
  }

   /**
   * Get observationVariableDbId
   * @return observationVariableDbId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getObservationVariableDbId() {
    return observationVariableDbId;
  }

  public void setObservationVariableDbId(String observationVariableDbId) {
    this.observationVariableDbId = observationVariableDbId;
  }

  public Phenotype season(String season) {
    this.season = season;
    return this;
  }

   /**
   * Get season
   * @return season
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSeason() {
    return season;
  }

  public void setSeason(String season) {
    this.season = season;
  }

  public Phenotype value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public Phenotype observationTimeStamp(String observationTimeStamp) {
    this.observationTimeStamp = observationTimeStamp;
    return this;
  }

   /**
   * Get observationTimeStamp
   * @return observationTimeStamp
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getObservationTimeStamp() {
    return observationTimeStamp;
  }

  public void setObservationTimeStamp(String observationTimeStamp) {
    this.observationTimeStamp = observationTimeStamp;
  }

  public Phenotype collector(String collector) {
    this.collector = collector;
    return this;
  }

   /**
   * Get collector
   * @return collector
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCollector() {
    return collector;
  }

  public void setCollector(String collector) {
    this.collector = collector;
  }

  public Phenotype uploadedBy(String uploadedBy) {
    this.uploadedBy = uploadedBy;
    return this;
  }

   /**
   * Get uploadedBy
   * @return uploadedBy
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUploadedBy() {
    return uploadedBy;
  }

  public void setUploadedBy(String uploadedBy) {
    this.uploadedBy = uploadedBy;
  }

  public Phenotype additionalInfo(Object additionalInfo) {
    this.additionalInfo = additionalInfo;
    return this;
  }

   /**
   * Get additionalInfo
   * @return additionalInfo
  **/
  @ApiModelProperty(example = "null", value = "")
  public Object getAdditionalInfo() {
    return additionalInfo;
  }

  public void setAdditionalInfo(Object additionalInfo) {
    this.additionalInfo = additionalInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Phenotype phenotype = (Phenotype) o;
    return Objects.equals(this.observationDbId, phenotype.observationDbId) &&
        Objects.equals(this.observationUnitDbId, phenotype.observationUnitDbId) &&
        Objects.equals(this.observationUnitName, phenotype.observationUnitName) &&
        Objects.equals(this.studyDbId, phenotype.studyDbId) &&
        Objects.equals(this.studyName, phenotype.studyName) &&
        Objects.equals(this.studyLocationDbId, phenotype.studyLocationDbId) &&
        Objects.equals(this.studyLocation, phenotype.studyLocation) &&
        Objects.equals(this.programName, phenotype.programName) &&
        Objects.equals(this.observationLevel, phenotype.observationLevel) &&
        Objects.equals(this.germplasmDbId, phenotype.germplasmDbId) &&
        Objects.equals(this.germplasmName, phenotype.germplasmName) &&
        Objects.equals(this.observationVariableId, phenotype.observationVariableId) &&
        Objects.equals(this.observationVariableDbId, phenotype.observationVariableDbId) &&
        Objects.equals(this.season, phenotype.season) &&
        Objects.equals(this.value, phenotype.value) &&
        Objects.equals(this.observationTimeStamp, phenotype.observationTimeStamp) &&
        Objects.equals(this.collector, phenotype.collector) &&
        Objects.equals(this.uploadedBy, phenotype.uploadedBy) &&
        Objects.equals(this.additionalInfo, phenotype.additionalInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(observationDbId, observationUnitDbId, observationUnitName, studyDbId, studyName, studyLocationDbId, studyLocation, programName, observationLevel, germplasmDbId, germplasmName, observationVariableId, observationVariableDbId, season, value, observationTimeStamp, collector, uploadedBy, additionalInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Phenotype {\n");
    
    sb.append("    observationDbId: ").append(toIndentedString(observationDbId)).append("\n");
    sb.append("    observationUnitDbId: ").append(toIndentedString(observationUnitDbId)).append("\n");
    sb.append("    observationUnitName: ").append(toIndentedString(observationUnitName)).append("\n");
    sb.append("    studyDbId: ").append(toIndentedString(studyDbId)).append("\n");
    sb.append("    studyName: ").append(toIndentedString(studyName)).append("\n");
    sb.append("    studyLocationDbId: ").append(toIndentedString(studyLocationDbId)).append("\n");
    sb.append("    studyLocation: ").append(toIndentedString(studyLocation)).append("\n");
    sb.append("    programName: ").append(toIndentedString(programName)).append("\n");
    sb.append("    observationLevel: ").append(toIndentedString(observationLevel)).append("\n");
    sb.append("    germplasmDbId: ").append(toIndentedString(germplasmDbId)).append("\n");
    sb.append("    germplasmName: ").append(toIndentedString(germplasmName)).append("\n");
    sb.append("    observationVariableId: ").append(toIndentedString(observationVariableId)).append("\n");
    sb.append("    observationVariableDbId: ").append(toIndentedString(observationVariableDbId)).append("\n");
    sb.append("    season: ").append(toIndentedString(season)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    observationTimeStamp: ").append(toIndentedString(observationTimeStamp)).append("\n");
    sb.append("    collector: ").append(toIndentedString(collector)).append("\n");
    sb.append("    uploadedBy: ").append(toIndentedString(uploadedBy)).append("\n");
    sb.append("    additionalInfo: ").append(toIndentedString(additionalInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

