/*
 * BrAPI implementation for PIPPA
 * A first draft implementation of the breeding API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.brapi.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * StudySearchEntry
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-31T12:16:05.949+02:00")
public class StudySearchEntry {
  @SerializedName("studyName")
  private String studyName = null;

  @SerializedName("studyDbId")
  private String studyDbId = null;

  @SerializedName("studyType")
  private String studyType = null;

  @SerializedName("seasons")
  private List<String> seasons = new ArrayList<String>();

  @SerializedName("trialDbId")
  private String trialDbId = null;

  @SerializedName("trialName")
  private String trialName = null;

  @SerializedName("startDate")
  private String startDate = null;

  @SerializedName("endDate")
  private String endDate = null;

  @SerializedName("active")
  private String active = null;

  public StudySearchEntry studyName(String studyName) {
    this.studyName = studyName;
    return this;
  }

   /**
   * Get studyName
   * @return studyName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStudyName() {
    return studyName;
  }

  public void setStudyName(String studyName) {
    this.studyName = studyName;
  }

  public StudySearchEntry studyDbId(String studyDbId) {
    this.studyDbId = studyDbId;
    return this;
  }

   /**
   * Get studyDbId
   * @return studyDbId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStudyDbId() {
    return studyDbId;
  }

  public void setStudyDbId(String studyDbId) {
    this.studyDbId = studyDbId;
  }

  public StudySearchEntry studyType(String studyType) {
    this.studyType = studyType;
    return this;
  }

   /**
   * Get studyType
   * @return studyType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStudyType() {
    return studyType;
  }

  public void setStudyType(String studyType) {
    this.studyType = studyType;
  }

  public StudySearchEntry seasons(List<String> seasons) {
    this.seasons = seasons;
    return this;
  }

  public StudySearchEntry addSeasonsItem(String seasonsItem) {
    this.seasons.add(seasonsItem);
    return this;
  }

   /**
   * Get seasons
   * @return seasons
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getSeasons() {
    return seasons;
  }

  public void setSeasons(List<String> seasons) {
    this.seasons = seasons;
  }

  public StudySearchEntry trialDbId(String trialDbId) {
    this.trialDbId = trialDbId;
    return this;
  }

   /**
   * Get trialDbId
   * @return trialDbId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTrialDbId() {
    return trialDbId;
  }

  public void setTrialDbId(String trialDbId) {
    this.trialDbId = trialDbId;
  }

  public StudySearchEntry trialName(String trialName) {
    this.trialName = trialName;
    return this;
  }

   /**
   * Get trialName
   * @return trialName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTrialName() {
    return trialName;
  }

  public void setTrialName(String trialName) {
    this.trialName = trialName;
  }

  public StudySearchEntry startDate(String startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStartDate() {
    return startDate;
  }

  public void setStartDate(String startDate) {
    this.startDate = startDate;
  }

  public StudySearchEntry endDate(String endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEndDate() {
    return endDate;
  }

  public void setEndDate(String endDate) {
    this.endDate = endDate;
  }

  public StudySearchEntry active(String active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getActive() {
    return active;
  }

  public void setActive(String active) {
    this.active = active;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StudySearchEntry studySearchEntry = (StudySearchEntry) o;
    return Objects.equals(this.studyName, studySearchEntry.studyName) &&
        Objects.equals(this.studyDbId, studySearchEntry.studyDbId) &&
        Objects.equals(this.studyType, studySearchEntry.studyType) &&
        Objects.equals(this.seasons, studySearchEntry.seasons) &&
        Objects.equals(this.trialDbId, studySearchEntry.trialDbId) &&
        Objects.equals(this.trialName, studySearchEntry.trialName) &&
        Objects.equals(this.startDate, studySearchEntry.startDate) &&
        Objects.equals(this.endDate, studySearchEntry.endDate) &&
        Objects.equals(this.active, studySearchEntry.active);
  }

  @Override
  public int hashCode() {
    return Objects.hash(studyName, studyDbId, studyType, seasons, trialDbId, trialName, startDate, endDate, active);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StudySearchEntry {\n");
    
    sb.append("    studyName: ").append(toIndentedString(studyName)).append("\n");
    sb.append("    studyDbId: ").append(toIndentedString(studyDbId)).append("\n");
    sb.append("    studyType: ").append(toIndentedString(studyType)).append("\n");
    sb.append("    seasons: ").append(toIndentedString(seasons)).append("\n");
    sb.append("    trialDbId: ").append(toIndentedString(trialDbId)).append("\n");
    sb.append("    trialName: ").append(toIndentedString(trialName)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

